project_id = "iomjazjwpcmosxinznyu"

[functions.create-payment]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.multibanco-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-order-email]
verify_jwt = true