project_id = "iomjazjwpcmosxinznyu"

[global.env]
FTP_HOST = "bashir.servidorpt.pt"
FTP_PORT = "21"
FTP_USER = "tiagogom"
FTP_PASSWORD = "kxuCUa8P.F74"
FTP_BASE_URL = "fotografiaescolar.duploefeito.com/fotos_alojamento/"